name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
        ports: ['3306:3306']
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/setup-php@v3
        with:
          php-version: '8.3'
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress
      - name: Install NPM dependencies
        run: npm ci
        working-directory: wp-content/themes/marjahans
      - name: Build theme assets
        run: npm run build
        working-directory: wp-content/themes/marjahans
      - name: PHP Lint
        run: composer lint --no-interaction
      - name: JS Format check
        run: npm run format:check
        working-directory: wp-content/themes/marjahans
      - name: PHP Unit tests
        run: composer test -- --testdox
      - name: E2E tests
        run: npm run test:e2e
        working-directory: wp-content/themes/marjahans
      - name: Deploy to Fly.io
        if: github.ref == 'refs/heads/main'
        uses: superfly/flyctl-actions@1.4
        with:
          args: "deploy --remote-only"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
